trigger:
  branches:
    include:
      - master

pool:
  name: CI-POOL-0
  demands: npm

resources:
  pipelines:
    - pipeline: websites-list-app
      source: websites-list-app
      branch: master
      trigger: true

steps:
  - task: NodeTool@0
    displayName: "use node 14"
    inputs:
      versionSpec: 14.x
      checkLatest: true

  - checkout: self
    displayName: "checkout"

  - task: Npm@1
    displayName: "npm ci"
    inputs:
      command: custom
      verbose: false
      customCommand: "ci --only=prod --registry http://localhost:4873/"

  - script: echo $(Build.Reason)
    displayName: "build reason"

  - powershell: Start-Sleep -Seconds 60
    displayName: "wait for 1m"

  - task: Npm@1
    displayName: "run dev tests"
    inputs:
      command: custom
      verbose: false
      customCommand: "run codeceptjs:dev:headless"
