trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*

resources:
  pipelines:
    - pipeline: app
      source: websites-list-app
      trigger:
        branches:
          include:
            - master

    - pipeline: data
      source: StaticWebsites-Data
      trigger:
        branches:
          include:
            - master
            - development

    - pipeline: sms
      project: SMS Publisher
      source: SMSApp
      trigger:
        branches:
          include:
            - develop

jobs:
  - job: static_websites
    condition: |
      or(
        ne(variables['Build.Reason'], 'ResourceTrigger'),
        ne(variables['Resources.TriggeringAlias'], 'sms')
      )
    pool:
      name: CI-POOL-0
    steps:
      - task: NodeTool@0
        displayName: 'use node 14'
        inputs:
          versionSpec: 14.x
          checkLatest: true

      - checkout: self
        displayName: 'checkout'

      - task: Npm@1
        displayName: 'npm ci'
        inputs:
          command: custom
          verbose: false
          customCommand: 'ci --only=prod'

      - powershell: Start-Sleep -Seconds 60
        displayName: 'wait for 1m'
        condition: |
          and(
            succeeded(),
            eq(variables['Build.Reason'], 'ResourceTrigger')
          )

      - powershell: npx cross-env HEADLESS=true url=dev.example-app.com env=dev codeceptjs run --grep "#static"
        displayName: 'run dev env tests'
        continueOnError: true
        condition: |
          and(
            succeeded(),
            or(
              ne(variables['Build.Reason'], 'ResourceTrigger'),
              eq(variables['Resources.TriggeringAlias'], 'app'),
              and(
                eq(variables['Resources.TriggeringAlias'], 'data'),
                eq(variables['resources.pipeline.data.sourceBranch'], 'refs/heads/development')
              )
            )
          )

      - powershell: npx cross-env HEADLESS=true url=prod.example-app.com env=prod codeceptjs run --grep "#static"
        displayName: 'run prod env tests'
        continueOnError: true
        condition: |
          and(
            succeeded(),
            or(
              ne(variables['Build.Reason'], 'ResourceTrigger'),
              eq(variables['Resources.TriggeringAlias'], 'app'),
              and(
                eq(variables['Resources.TriggeringAlias'], 'data'),
                eq(variables['resources.pipeline.data.sourceBranch'], 'refs/heads/master')
              )
            )
          )

      - task: PublishPipelineArtifact@1
        displayName: 'publish data'
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/output

  - job: sms_static_websites
    condition: |
      or(
        ne(variables['Build.Reason'], 'ResourceTrigger'),
        eq(variables['Resources.TriggeringAlias'], 'sms')
      )
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - task: NodeTool@0
        displayName: 'use node 14'
        inputs:
          versionSpec: 14.x
          checkLatest: true

      - checkout: self
        displayName: 'checkout'

      - task: Npm@1
        displayName: 'npm ci'
        inputs:
          command: custom
          verbose: false
          customCommand: 'ci --only=prod'

      - bash: npx cross-env HEADLESS=true url=sms-app.example.com codeceptjs run --grep "#sms"
        displayName: 'run sms static websites tests'

      - task: PublishPipelineArtifact@1
        displayName: 'publish data'
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/output
